### PR TITLE
bugfix: do not add karmada.io/managed selector when watching single resource

### PR DESCRIPTION
**Pull request by wm775825**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

We support getting all resources through labelSelector with list/watch interface by #10 .

However, when we watch single resource by `kubectl get deploy xxx -w`, for example, we can not receive watch events, since  we add `karmada.io/managed != true` requirement, which cannot be met by deployment `xxx`.

If we want to use `kubectl get deploy xxx -w -l fleet-resource-view`, we will receive an error `error: name cannot be provided when a selector is specified` from kubectl.

So we should do nothing if a user want to watch single resource.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
> However, when we watch single resource by kubectl get deploy xxx -w, for example, we can not receive watch events, since we add karmada.io/managed != true requirement, which cannot be met by deployment xxx.

Does this behavior target resources in the karmada control plane or resources in member clusters?

**Comment by wm775825** [comment]
> > However, when we watch single resource by kubectl get deploy xxx -w, for example, we can not receive watch events, since we add karmada.io/managed != true requirement, which cannot be met by deployment xxx.
> 
> Does this behavior target resources in the karmada control plane or resources in member clusters?

The single resource which is propagated by karmada and therefore has `karmada.io/managed: true` label.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/cc @RainbowMango

**Pull request merged**
